### ISSUE TITLE
Maintainer request

### ISSUE THREAD

**Issue by NewAlexandria** [toplap/awesome-livecoding#40]
I'd like to see this in the AwesomeList.  I'd like to be a mainter for such editorial purposes.  Glad to help with other things.  Thank you

**Comment by lvm** [comment]
Hi there,
some time ago i created a PR there, but the amount of changes required plus the fact that this list should be treated as an extension of this person project, made me regret that decision.
personally, i'm not interested any longer on being listed there. not sure how the rest feels about this.

for the record, here's the pull request
https://github.com/sindresorhus/awesome/pull/1049

**Comment by NewAlexandria** [comment]
Style consistency is a common request for any collaborative codebase or project, so hopefully you can be willing to let someone else maintain that, who like to do such things.

**Comment by lvm** [comment]
Sure thing, but one of the points was to remove/alter the "tags" in the list (such as `GNU/Linux`, `FOSS`, etc.) and i'm not interested in doing so. :man_shrugging:

**Comment by shawnlawson** [comment]
What is the benefit to not being listed on sindresorhus/awesome? Creative coding is listed there. Not that live-coding is in direct competition with CC, but would be helpful to be acknowledged there, yes?

**Comment by NewAlexandria** [comment]
@lvm I tried the look of putting tags on their own line. Thoughts?

https://github.com/NewAlexandria/awesome-livecoding

I realize it's a different look, but I — your friendly internet strange, it seems - votes that this is at least more readable than the existing style. 

I also took a stab at a number of other linting, since I was sitting around fiddling on it while waiting on other code.

**Comment by NewAlexandria** [comment]
hopeful and polite bump

**Comment by lvm** [comment]
Hi @NewAlexandria,
to be sincere, i couldn't care less about the awesome-list _but_ since you made all these changes (and am grateful for this), won't be completely stubborn and merge these changes.   
but there are a couple of observations i'd like to make about your changes (mostly cosmetics and nothing really that serious):

* we should need to update this file as well (to match this new format)
https://github.com/toplap/awesome-livecoding/blob/master/contributing.md
* why is there a _blank_ line between the projects and its tags? is it possible to do something like this:
```
[project](url) - Description {double space, line break} 
`list` `of` `tags`
```
is it because it throws an error/warning using that ~lovely~ awesome-lint? 

and once again, thanks for your work

**Comment by NewAlexandria** [comment]
commented added to the PR

**Comment by NewAlexandria** [comment]
Thanks for the merge!

**Comment by lvm** [comment]
Done! Thanks for your work @NewAlexandria
